# Generated by Django 3.1.6 on 2021-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_city', models.CharField(max_length=50)),
                ('p_state', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('area_code', models.IntegerField(default=91)),
                ('phone', models.CharField(max_length=12)),
                ('p_type', models.CharField(max_length=50)),
                ('p_address', models.CharField(max_length=1024)),
                ('execting_cus', models.BooleanField(default=False)),
                ('p_price', models.IntegerField(default=0)),
                ('p_time_area', models.CharField(max_length=50)),
                ('p_rooms_available', models.IntegerField()),
                ('p_floor_no', models.IntegerField()),
                ('p_sharing_member', models.IntegerField()),
                ('tenants_preffered', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='p_images')),
                ('p_amanities', models.CharField(max_length=200)),
                ('house_rules', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
