# Generated by Django 3.1.5 on 2021-05-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('owner_id', models.IntegerField(default=0)),
                ('Due_date', models.DateField()),
                ('p_name', models.CharField(max_length=100)),
                ('p_type', models.CharField(max_length=100)),
                ('p_address', models.CharField(max_length=100)),
                ('p_state', models.CharField(max_length=100)),
                ('Check_IN', models.DateTimeField()),
                ('Check_OUT', models.DateTimeField()),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('tel', models.CharField(default=None, max_length=12, null=True)),
                ('Phone_no', models.CharField(default=None, max_length=15, null=True)),
                ('People', models.IntegerField(default=None, max_length=12, null=True)),
                ('p_price', models.IntegerField(default=None, max_length=12, null=True)),
                ('T_price', models.IntegerField(default=None, max_length=12, null=True)),
                ('F_price', models.IntegerField(default=None, max_length=12, null=True)),
                ('Days', models.IntegerField(default=None, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_country', models.CharField(choices=[('Australiya', 'Australiya'), ('Usa', 'Usa'), ('India', 'India')], max_length=50, null=True)),
                ('p_state', models.CharField(choices=[('Gujarat', 'Gujarat'), ('Rajasthan', 'Rajasthan'), ('Panjab', 'Panjab'), ('Hariyana', 'Hariyana')], max_length=50, null=True)),
                ('p_city', models.CharField(choices=[('Rajkot', 'Rajkot'), ('Ahmedabad', 'Ahmedabad'), ('Vadodara', 'Vadodara')], max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('area_code', models.IntegerField(default=91)),
                ('phone', models.CharField(max_length=12)),
                ('p_type', models.CharField(choices=[('PG', 'PG'), ('Apartment', 'Apartment')], max_length=50)),
                ('p_address', models.CharField(max_length=1024)),
                ('execting_cus', models.BooleanField(default=False)),
                ('p_price', models.IntegerField(default=0)),
                ('p_time_area', models.CharField(max_length=50)),
                ('p_rooms_available', models.IntegerField(default=1)),
                ('p_floor_no', models.IntegerField(default=0)),
                ('p_sharing_member', models.IntegerField(default=1)),
                ('tenants_preffered', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Family', 'Family')], max_length=50)),
                ('photo', models.ImageField(max_length=2000, upload_to='p_images')),
                ('photo1', models.ImageField(max_length=2000, upload_to='p_images')),
                ('photo2', models.ImageField(max_length=2000, upload_to='p_images')),
                ('photo3', models.ImageField(max_length=2000, upload_to='p_images')),
                ('photo4', models.ImageField(max_length=2000, upload_to='p_images')),
                ('p_amanities', models.CharField(max_length=200)),
                ('house_rules', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.user_registration')),
            ],
        ),
    ]
