# Generated by Django 3.1.6 on 2021-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='p_floor_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='p_rooms_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='p_sharing_member',
            field=models.IntegerField(default=1),
        ),
    ]
