# Generated by Django 3.1.6 on 2021-03-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgas', '0002_auto_20210307_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='p_city',
            field=models.CharField(blank=True, choices=[('Rajkot', 'Rajkot'), ('Ahmedabad', 'Ahmedabad'), ('Vadodara', 'Vadodara')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='p_state',
            field=models.CharField(choices=[('Gujarat', 'Gujarat'), ('Rajasthan', 'Rajasthan'), ('Panjab', 'Panjab'), ('Hariyana', 'Hariyana')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='p_type',
            field=models.CharField(choices=[('PG', 'PG'), ('Apartment', 'Apartment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenants_preffered',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Family', 'Family')], max_length=50),
        ),
    ]
