# Generated by Django 3.1.6 on 2021-03-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opgas', '0003_auto_20210307_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='p_images'),
        ),
    ]
