# Generated by Django 3.1.5 on 2021-03-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opgas', '0006_property_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='author',
        ),
    ]
